# Generated by Django 5.1.3 on 2024-12-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0012_likedreply_reply_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
