# Generated by Django 5.1.3 on 2024-12-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0013_remove_post_url_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='artist',
        ),
    ]
