# Generated by Django 5.1.3 on 2024-12-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0014_remove_post_artist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={},
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
